export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description: 'Get access to our exclusive app',
  buttonLabel: 'Get Started',
  imgStart: false,
  img: require('../../images/svg-1.svg').default,
  alt: '.SVG',
  dark: true,
  primary: true,
  dartText: false,
};

export const homeObjTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Unlimited Access',
  headline: 'Unlimited Transactions with zero fees',
  description: 'Get access to our exclusive app',
  buttonLabel: 'Learn More',
  imgStart: true,
  img: require('../../images/svg-2.svg').default,
  alt: '.SVG',
  dark: false,
  primary: false,
  dartText: true,
};

export const homeObjThree = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description: 'Get access to our exclusive app',
  buttonLabel: 'Start Now',
  imgStart: false,
  img: require('../../images/svg-3.svg').default,
  alt: '.SVG',
  dark: false,
  primary: false,
  dartText: true,
};
